### ISSUE TITLE
Issues with ground temperature when using SUEWS-SPARTACUS

### ISSUE THREAD

**Issue by megstretton** [UMEP-dev/SUEWS#100]
When setting all ground surface (not buildings) as impervious, the ground temperature/paved temperature does not vary when the morphology is changed - for example if SUEWS-SPARTCAUS is used with multiple layers, or if the building fraction is decreased/increased.

**Comment by sunt05** [comment]
Hi @megstretton, I had a closer look and found there's actually difference–minimal though–in the surface temperature of paved surfaces, which is different from what I recall last time you showed me:

![9374beea-76e0-4e4c-b251-41316cd08b05](https://user-images.githubusercontent.com/1802656/168794935-f5c4482d-efb7-4a99-81f0-d1edebd3ba5e.png)

Anyway, I believe there are more tweaks should do to get this work better.

So maybe you can post your results here for our record and we can then work further on this issue.

**Comment by megstretton** [comment]
Hi @sunt05. Thanks for looking at this. I've attached two results for a summer day. The first is with varying building fraction at the surface (that is constant up to 25 m with 4 layers) from 0.11 - 0.66. I agree here that there is definetely a difference in ground temperature (paved) although this is small.

![test_pavedT_buidlingfrac](https://user-images.githubusercontent.com/39263347/170511591-bc3d88d9-e5a7-4e24-9f7c-2b3818f8d2e5.png)

The second (below) shows three runs with different numbers of layers - one with a different maximum height - but with the same building fraction. In this case we see only small differences in the paved surface temperature.

![test_pavedT_layers](https://user-images.githubusercontent.com/39263347/170511600-97bbf003-a2da-45c7-80d8-376898e2cba8.png)

**Comment by sunt05** [comment]
Hopefully, my answer above addresses this issue, so I'll close it for now. Otherwise, feel free to re-open and provide more details to help resolve it.
