### ISSUE TITLE
Surface temperatures in SUEWS

### ISSUE THREAD

**Issue by megstretton** [UMEP-dev/SUEWS#122]
There is an issue with surface temperatures when using both SS and NARP, when using the new ESTMExt. After examining both the surface temperatures output, and the fluxes, I think this is due to a tempertaure averaging issue, or that the wrong temperatures are being output - as the fluxes themselves are consistent between the two models, but the temperatures are not...

My understanding of the temperature averaging is that (when no vegetation is included) the Ts_Wall_X and Ts_Roof_X (e.g., test1_2017_ESTMExt_5) are combined with the roof/wall fraction profiles (e.g., GridLayout.nml) to form the Ts_Bldgs (e.g.,test1_2017_ESTMExt_5 ). Then, all surface types are combined to get (when no vegetation is included) the bulk surface temperature (Tsurf, test1_2017_SUEWS_5).

The SUEWS-NARP-ESTM temperatures for each facet are extremely high, and do not vary much between each facet, and the bulk surface temperature (Tsurf in SUEWS output file) is much lower, and reasonable when doing a quick calculation with Lup. The Tsurf appears to be too low to be a combination of the T_Bldgs and T_Paved values in this simulation, and neither do the T_Wall and T_Roof. Also, the T_Bldgs seems to be getting to nearly 90 C.

Additionally, the SUEWS-SS-ESTM facet temperatures are very low, and have little variation across height levels (I use a 9-layer run), and the roof temperatures have less spread and lower magnitudes than the wall temperatures. In this simulation the T_Paved and T_Bldgs seem feasible to have been combined to get the Tsurf value. However, the T_Wall and T_Roof are too low compared to the T_Bldgs.

![test_Ttest_2807](https://user-images.githubusercontent.com/39263347/181707793-2d00ebd6-2454-45e0-99fe-5eb47d933869.png)

**To Reproduce**
Files: 
[SUEWS_NARP_ESTM_15forcing_5out.zip](https://github.com/UMEP-dev/SUEWS/files/9209877/SUEWS_NARP_ESTM_15forcing_5out.zip)
[SUEWS_SS_ESTM_9lay_15forcing_5out.zip](https://github.com/UMEP-dev/SUEWS/files/9209878/SUEWS_SS_ESTM_9lay_15forcing_5out.zip)

**Comment by sunt05** [comment]
Thanks @megstretton for these plots - very helpful - I'll look into this issue next week.

**Comment by sunt05** [comment]
just to leave an update on this issue - @megstretton and I found the issue is in the abnormally small incoming solar radiation received at the building facets that are normalised by building fractions, which need to be denormalised to recover the correct values for other calculations in SUEWS.

**Comment by sunt05** [comment]
just to leave a note here for the quantitative relations between SS output variables:

$$Q_n= KTop_n+ LTop_n$$

$$KTopNet = \sum_{i}{KRfNet_i}+\sum_{i}{KWallNet_i}+KGrndNet$$

$$LTopNet = \sum_{I}{LRfNet_i}+\sum_{I}{LWallNet_i}+LGrndNet$$

**Comment by sunt05** [comment]
addressed long ago - but please reopen if this persists.
