### ISSUE TITLE
Problems in running compiled SUEWS on mac computer

### ISSUE THREAD

**Issue by ljarvi** [UMEP-dev/SUEWS#127]
I'm using gfortran on macOS Monterey Version 12.5 to compile SUEWS. I'm able to compile, but when running the model it complains on most runs at some point the below error message and kind of frozes:

Program received signal SIGILL: Illegal instruction.

Backtrace for this error:

Program received signal SIGTRAP: Trace/breakpoint trap.

Backtrace for this error:

I think this is due to the compiler that I'm using and that it might be more strict than some other compilers. But here any help to get rid of this issue would be appreciated.

**Comment by sunt05** [comment]
input data from Leena for further debugging
[SUEWS-greenroof.zip](https://github.com/UMEP-dev/SUEWS/files/9415958/SUEWS-greenroof.zip)
.
