### ISSUE TITLE
maintain numpy consistency with UMEP

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/SUEWS#133]
As SuPy, or more specifically the underlying supy-driver, is dependent on [numpy ABI](https://numpy.org/doc/stable/user/depending_on_numpy.html) and meanwhile a key component in UMEP, it would be better to maintain version consistency with the numpy used in QGIS to allow better compatibility of UMEP with the QGIS ecosystem.

**Comment by sunt05** [comment]
As of 04 Sep 2022, `numpy==1.20.2` is used with `QGIS=~3.10.X`.

**Comment by sunt05** [comment]
a useful package for addressing this issue: https://github.com/scipy/oldest-supported-numpy/

**Comment by biglimp** [comment]
I am not sure what I can do about this as it is the supy -driver that need to be working with the QGIS numoy version. Can you compile the f2py to work with a specific version?

**Comment by sunt05** [comment]
> I am not sure what I can do about this as it is the supy -driver that need to be working with the QGIS numoy version. 

Hi @biglimp you are included in this loop mostly for updates and some tests when a fix is done.

> Can you compile the f2py to work with a specific version?

Yes, I'll set up new GH workflows to get more compatible supy-driver built there following the approaches suggested above.
