### ISSUE TITLE
Create a diagnostic function to save user's model states

### ISSUE THREAD

**Issue by ghost** [UMEP-dev/SUEWS#160]
*@suegrimmond commented on Jul 2, 2019, 11:23 AM UTC:*

**Describe the Issue**
Add to the manual -- then send a link -- when someone encounters a problem -- then instructions etc will become clearer and can be used by others

**Location**
Problem from a User -

**Screenshots**

**Additional context**
Please do the following:

1.  dump `df_state_init` and `df_forcing` as pickle files:

```
df_state_init.to_pickle("df_state_init.pkl")
df_forcing.to_pickle("df_forcing.pkl")

```

2.  save the `.pkl` files and your notebook into one archive file (e.g., test.zip)

*This issue was moved by [sunt05](https://github.com/sunt05) from [sunt05/SuPy#86](https://github.com/sunt05/SuPy/issues/86).*

**Comment by sunt05** [comment]
This has been fixed - when a fatal error is triggered, a debugging zip archive will be generated on the user side.
