### ISSUE TITLE
merge supy docs into the SUEWS docs site

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/SUEWS#163]
- [x] give an example how `suews-run` should be used
- [x] use local CSV files to build supy docs
- [x] fix all references to each other (i.e. suews <-> supy)

**Comment by RussellGl** [comment]
Just reporting that the SUEWS docs site is down right now or is there a new link? dont know if this is related.

**Comment by sunt05** [comment]
@RussellGl were you using this one? https://suews.readthedocs.io/

It is working for me.

**Comment by sunt05** [comment]
close this issue as it has been done via #165
