### ISSUE TITLE
Biogenic emissions not outputed- Values are zeros

### ISSUE THREAD

**Issue by phemiobe** [UMEP-dev/SUEWS#170]
Hi, 
In an attempt to simulate the biogenic emissions (Fc FcPhoto FcRespi FcMetab FcTraff FcBuild FcPoint) with SuPy. I have got no values other than
[3_2018_SUEWS_60.txt](https://github.com/UMEP-dev/SUEWS/files/11026769/3_2018_SUEWS_60.txt)
 zeros for the biogenic emissions column. Perhaps something is missing from my input. Any clue would be appreciated. Thanks. kindly see the attached output of a grid.

Thanks for helping out

**Comment by phemiobe** [comment]
from( https://suews.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/SUEWS_BiogenCO2.html)
I can see that The BiogenCO2 part is under development and not ready for use. Can anyone please provide some more info..

thanks

**Comment by phemiobe** [comment]
r

**Comment by phemiobe** [comment]
Related to #139 and #146

**Comment by yyssqq** [comment]
Hello, at the risk of interrupting, I don't know how to contact you. So here is a message for you. I noticed that you are also using the carbon module of SUEWS and I have the same problem as you, but when setting emissionmethod=45, Fcpho=0 and FcRespi is constantly constant. Not sure if there is a problem, if there is any info you can provide?

> Related to #139 and #146
