### ISSUE TITLE
Possibility to turn off SUEWS-SPARTACUS model

### ISSUE THREAD

**Issue by pfung-maker** [UMEP-dev/SUEWS#173]
I'm now using the latest version of SuPy and trying to replicate a previous study which did not use a SUEWS-SPARTACUS module. I did not include a SUEWS-SPARTACUS.nml, but it seems that it is necessary to include one in order to continue with the stimulation. Is there an option to turn that module off?

Thank you in advance.

The  version I used:
SuPy versions
-------------
supy: 2022.9.22
supy_driver: 2021a14.post3

**Comment by sunt05** [comment]
unfortunately the version you are using cannot skip this SS.nml file but you can find one [here](https://github.com/UMEP-dev/SUEWS/blob/master/src/supy/supy/sample_run/Input/SUEWS_SPARTACUS.nml) - once it's in place, the error should be gone.

**Comment by sunt05** [comment]
Hopefully, my answer above addresses this issue, so I'll close it for now. Otherwise, feel free to re-open and provide more details to help resolve it.
