### ISSUE TITLE
Error about sp.run_supy

### ISSUE THREAD

**Issue by tyhzxc** [UMEP-dev/SUEWS#178]
**Describe the Issue**
sp.run_supy report error when set conductance.
```
df_state_init.loc[:, ("maxconductance", "(2,)")] = 13.86
df_state_init.loc[:, "g2"] = 104.47
df_state_init.loc[:, "g3"] = 0.79
df_state_init.loc[:, "g4"] = 0.59
df_state_init.loc[:, "g5"] = 37.24
df_state_init.loc[:, "g6"] = 0.025

```

**Comment by tyhzxc** [comment]
[test.zip](https://github.com/UMEP-dev/SUEWS/files/11303863/test.zip)

**Comment by sunt05** [comment]
> **Describe the Issue** sp.run_supy report error when set conductance.
> 
> ```
> df_state_init.loc[:, ("maxconductance", "(2,)")] = 13.86
> df_state_init.loc[:, "g2"] = 104.47
> df_state_init.loc[:, "g3"] = 0.79
> df_state_init.loc[:, "g4"] = 0.59
> df_state_init.loc[:, "g5"] = 37.24
> df_state_init.loc[:, "g6"] = 0.025
> ```

Please see here to update these names:

https://github.com/UMEP-dev/SUEWS/blob/df1cfcf434ecdbd5d05ffa13dba8fe266743038e/src/supy/supy/_check.py#L321-L326

**Comment by sunt05** [comment]
@tyhzxc  is this resolved? if so, please close it. thanks!
