### ISSUE TITLE
r^2  label in sp.util._plot.plot_comp()

### ISSUE THREAD

**Issue by tyhzxc** [UMEP-dev/SUEWS#179]
**Describe the Issue**
In the code below,  r^2 should be equal to r_value^2?

`sns.regplot(
        x=val_x,
        y=val_y,
        # data=df_var_fit,
        ax=ax,
        fit_reg=True,
        line_kws={
            "label": "\n".join(
                [
                    f"y={slope:.2f}x{'+' if intercept > 0 else ''}{intercept:.2f}",
                    f"$R^2$={r_value:.4f}",
                    f"MAE={mae:.2f}",
                    f"MBE={mbe:.2f}",
                    f"n={df_var_fit.shape[0]}",
                ]
            )
        },`

**Screenshots**

**Additional context**

**Comment by sunt05** [comment]
Please add a link to the code snippet - thanks! @tyhzxc

**Comment by tyhzxc** [comment]
https://github.com/UMEP-dev/SUEWS/blob/df1cfcf434ecdbd5d05ffa13dba8fe266743038e/src/supy/supy/util/_plot.py#L175-L197

**Comment by sunt05** [comment]
Thanks @tyhzxc !
