### ISSUE TITLE
Incompatibility with the latest version of pandas(SUEWS)

### ISSUE THREAD

**Issue by Kangarooboxer** [UMEP-dev/SUEWS#181]
<img width="611" alt="bab05e79ec3afe1cc6bbe07784e9ddc" src="https://github.com/UMEP-dev/SUEWS/assets/123106290/d0a6279c-235f-40ea-99b2-62615fb92fb6">

<img width="609" alt="bd213bbee51867f987b051eddeb26e7" src="https://github.com/UMEP-dev/SUEWS/assets/123106290/079e317b-9ebd-42eb-9abf-b38547b9fe3a">

<img width="1264" alt="f761051383860735169af185de61094" src="https://github.com/UMEP-dev/SUEWS/assets/123106290/5234794b-520a-497c-8b47-9cc609b4e905">

Hi, Dr. Sun @sunt05 ,
Ruidong and I just found some some problems about the compatibility of pandas when running the code "df_state_init" in the "quick-start.ipynb" file provided by the first section of the tutorial you sent me.

When we used the 2.0.1 version pandas(the latest version?), the code didn't work, we tried run after we ran the code in Anaconda Powershell Promt in the forsy screenshot.

After we changed the version of pandas to 1.4.4(Second screenshot ), and tried to run all the codes in VS code, the "df_state_init" managed to work(third screenshot).

**Comment by sunt05** [comment]
Thanks @Kangarooboxer Tianyin for reporting this issue - good job!

**Comment by sunt05** [comment]
this issue has been fixed in a recent dev version b3b9394b76738255ea8808f4e7fda72c01926150
