### ISSUE TITLE
RSS problem

### ISSUE THREAD

**Issue by LllC-mmd** [UMEP-dev/SUEWS#197]
**Describe the Issue**

Abnormal RSS value during QE calculation - e.g. negative values

**Comment by sunt05** [comment]
add [test-case.zip](https://github.com/UMEP-dev/SUEWS/files/11873945/test-case.zip) to reproduce the error.

**Comment by sunt05** [comment]
the issue is in the porosity setting - when porosity reaches 1 - which is not reasonable, the effective deciduous tree height becomes 0 and thus leads to various issues due to the unreasonable roughness length.

some restriction should be introduced to the porosity.
