### ISSUE TITLE
Potential bugs for SuPy simulation (specifically 'df_state' in the case of Shanghai grid experiment)

### ISSUE THREAD

**Issue by Kangarooboxer** [UMEP-dev/SUEWS#202]
![image](https://github.com/UMEP-dev/SUEWS/assets/123106290/05a10542-5d5d-42dc-95b5-cee2b4529a95)
Under the grid experiment of CH-Shanghai, the 'df_state' data here are weird, all grids have the same value and the location data (longitude and latitude) seems not reasonable:
![image](https://github.com/UMEP-dev/SUEWS/assets/123106290/62a57e61-467c-4085-aeb9-dad3b9606163)

**Comment by sunt05** [comment]
please submit this issue in the original supy-lcz repo - this issue has nothing to do with the SUEWS model itself.
