### ISSUE TITLE
SuPy simulation period issue (CH-Shanghai grid experiment case)

### ISSUE THREAD

**Issue by Kangarooboxer** [UMEP-dev/SUEWS#203]
The SuPy simulation period for Shanghai has been changed to 2021-01-07 →2021-07-07(The default period was 2021-07-01 → 2021-07-07). And it seems like any longer period than the default period will made the terminal get stuck when terminal dispalys 'SuPy is running in parallel mode', and the new data of input or output failed to be updated:
![image](https://github.com/UMEP-dev/SUEWS/assets/123106290/0d1717c8-5fa2-4e0d-9b9f-af4ab986e0a3)
Terminal code run here: python -m runner.runner CH-Shanghai --run-type grid --grid-size 300 --grid-boxes 3 --metforc-src era5land --urbdesc-src lcz_updated --sitelist sitelist_custom --download-era5

**Comment by sunt05** [comment]
please submit this issue in the original supy-lcz repo - this issue has nothing to do with the SUEWS model itself.
