### ISSUE TITLE
Benchmarking EHC

### ISSUE THREAD

**Issue by LllC-mmd** [UMEP-dev/SUEWS#208]
- compare EHC with results from scipy's 1D heat conduction solver
- compare results with two types of lower BCs: fixed temperature and zero-flux

**Comment by LllC-mmd** [comment]
If EHC is OK, we will move onto the testing of different land cover composition using SampleData from SUEWS

**Comment by LllC-mmd** [comment]
- EHC-based 1D heat conduction simulation

Case I: fixed temperature boundary where $T_L = 12$ and $T_R  = 10$.

**Comment by sunt05** [comment]
simulated surface temperatures of a paved surface on a summer day using different heat conductivities:
![image](https://github.com/UMEP-dev/SUEWS/assets/1802656/52ba3c4c-ff70-47a5-9bd8-33375dbdf66e)

**Comment by sunt05** [comment]
these simple tests show the acceptable performance of the module - a more comprehensive evaluation will be left for another dedicated issue/thread.
