### ISSUE TITLE
QE, QH T2 results lost in certain conditions

### ISSUE THREAD

**Issue by XiaoxiongXie** [UMEP-dev/SUEWS#209]
In some cases QE, QH, T2 outputs are lost (become NaN), i.e. 19 Feb here:

![download](https://github.com/UMEP-dev/SUEWS/assets/33037107/6b14d749-5607-49cb-8dd6-b20fed6666a5)

Input files:
[df_state_init_test.csv](https://github.com/UMEP-dev/SUEWS/files/12182181/df_state_init_test.csv)
[df_forcing_test.csv](https://github.com/UMEP-dev/SUEWS/files/12182183/df_forcing_test.csv)

Seems to be a QE issue, but the problem will go if:
- using the sample 2012 forcing data
- or increasing the QF coefficients (qf_a, b, c), in this case changing qf_c from 0.0012 to 0.0054
- or changing net radiation method to 1 (using forcing Ldown), currently 3 (calculated from T and RH)

supy: 2022.4.7 
supy_driver: 2021a5

Similar problem is also found in supy 2022.8.5.dev0.

**Comment by sunt05** [comment]
@XiaoxiongXie please close this issue if this has been resolved - otherwise please follow up with more info.
