### ISSUE TITLE
Issue in calculating irrigation

### ISSUE THREAD

**Issue by ljarvi** [UMEP-dev/SUEWS#228]
I'm running SUEWS with irrigation on in such a way that all irrigation is manual irrigation (Faut is zero in SUEWS_Irrigation.txt). The model calculates daily irrigation and prints it correctly to the daily SUEWS output file. However, in the hourly output file the irrigation column is all zero and based how the evaporation looks like, also the calculation of evaporation is not getting the irrigated water. I have tried to track down where the issue is in the source code, but have failed to find it out. If Faut is not zero in SUEWS_Irrigation.txt, then also hourly irrigation is produced.
 
I enclosed the zip file with the issue present.

**Version and platform (please complete the following information):**
- SUEWS version: [development version] 
- OS: macOS

**Additional context**
[sample_runHel.zip](https://github.com/UMEP-dev/SUEWS/files/12882504/sample_runHel.zip)

**Comment by sunt05** [comment]
Hello @ljarvi, could you please specify which code commit is causing this issue?

**Comment by ljarvi** [comment]
Good question. I think it is commit version eade2e12a5d6867170c56cba5f6b915f6f502732. I cloned the code on 27th September here from github

**Comment by sunt05** [comment]
Thanks @ljarvi ! 

Once I've finished teaching for the week tomorrow, I'll take a closer look and get back to you here.
