### ISSUE TITLE
Problem when running certain morphologies with multi-layer SUEWS-SS

### ISSUE THREAD

**Issue by megstretton** [UMEP-dev/SUEWS#252]
In a few situations, using supy version 2023.7.3.dev0 with the multi-layer SS doesn't work. In these cases, when run with another branch (), SUEWS did run before. This has been tested by swapping out the morphology into a working SUEWS run - and so it is not an issue from the input files themselves.

It was thought this might be an issue due to two layers having the same building fraction across two layers, and hence this would stop the model working on basic cuboid cases, but looking back at a 9 layer simulation, all layers have different building fraction and so this is not the case.

When the simulations are run, the model appears to run, with the error file saying 'Run complete'. But, the run time is significantly shorter than expected and the output file is incomplete for most/all timesteps.

The files below are:
AVL_9 - a 9-layer SUEWS-SS simulation that breaks
AVL_6 - a 7-layer version of the 9-layer scene that also breaks 
AVL_6_298 - a 7-layer simulation with different morphology that runs correctly

[AVL_6_298.zip](https://github.com/UMEP-dev/SUEWS/files/14541176/AVL_6_298.zip)

[AVL_6.zip](https://github.com/UMEP-dev/SUEWS/files/14541171/AVL_6.zip)

[AVL_9.zip](https://github.com/UMEP-dev/SUEWS/files/14541162/AVL_9.zip)

**Comment by megstretton** [comment]
Looking into this again, I have taken two new grids, with high building fraction and mean building height. These are from London and NYC.

I have run these scenes for two layer configurations, with 6/7 layers and 9 layers. At first, the 7-layer simulations do not run, however when modifying them so that the building fraction is never the same across two layers, they do run. The 9-layer simulations do not run. So, the issues above are still present in new grids.

The issues appear to be:
- Simulations with SUEWS-SS do not run if the building fraction is the same in consecutive layers.
- Simulations with more than 7 layers (I have looked at 9 but will likely be the case for others) do not run to completion, despite the capacity of SUEWS-SS for up to 15 layers.

The corresponding files are:
[AVL_9_vars333.zip](https://github.com/user-attachments/files/15614524/AVL_9_vars333.zip)
[AVL_9_vars273.zip](https://github.com/user-attachments/files/15614530/AVL_9_vars273.zip)
[AVL_6_vars273.zip](https://github.com/user-attachments/files/15614550/AVL_6_vars273.zip)
[AVL_6_vars333.zip](https://github.com/user-attachments/files/15614536/AVL_6_vars333.zip)

**Comment by sunt05** [comment]
Thanks for the further info.


> The issues appear to be:
> 
> * Simulations with SUEWS-SS do not run if the building fraction is the same in consecutive layers.

This is a known bug to be fixed.

> * Simulations with more than 7 layers (I have looked at 9 but will likely be the case for others) do not run to completion, despite the capacity of SUEWS-SS for up to 15 layers.

Have you tested a case with 8 layers?
