### ISSUE TITLE
Unexpected Behavior/Error When Loading Sample Data in SuPy Version 2023.2.23.dev0

### ISSUE THREAD

**Issue by yyssqq** [UMEP-dev/SUEWS#253]
Dear UMEP team,

I hope this message finds you well.

**Describe the bug**
Encountered an issue when trying to load and utilize sample data in SuPy. The process includes initializing state data and forcing data but leads to unexpected behavior/error (the exact nature of the error isn't detailed in the provided excerpt).

**To Reproduce**
Attempting to load sample data using sp.load_SampleData(), which is where the issue 
 arise.
[JupyterOutput.txt](https://github.com/UMEP-dev/SUEWS/files/14785355/JupyterOutput.txt)

**Version and platform (please complete the following information):**
- SuPy Version: 2023.2.23.dev0
- OS: Windows 11 Professional
- python version: 3.11.7

**Additional context**
I am particularly interested in utilizing SuPy for simulating biogenic carbon fluxes. However, I noticed in the documentation/tutorial that the module for biogenic carbon flux simulation was not ready for use. Given my specific interest in this feature, I am curious if the current version of SuPy (2023.2.23.dev0) has introduced the capability for biogenic carbon flux output or if there are any plans to include this feature in the near future. Any information or guidance on this matter would be greatly appreciated, as it directly influences the scope of my research and simulation projects.

Warm regards,
Shaoqi

**Comment by sunt05** [comment]
Hi @yyssqq, this issue appears to stem from a deprecation in the latest `pandas`. 

Please upgrade to the newest supy dev version: `pip install supy==2024.3.25.dev0`.

Let us know if any problems persist.
