### ISSUE TITLE
Error importing supy

### ISSUE THREAD

**Issue by putupass** [UMEP-dev/SUEWS#265]
**Describe the Issue**
Error importing supy. Operating system etc. had been checked. ValueError: 3 columns passed, passed data had 4 columns

**Is `supy_debug-xxxxxxxx.zip` generated?**
No

**Screenshots**

[Error Report.zip](https://github.com/user-attachments/files/15726362/Error.Report.zip)
![Screenshot 2024-06-07 155137](https://github.com/UMEP-dev/SUEWS/assets/1802656/9f3795c2-9e31-4be4-a2ec-72bba7046e92)
![Screenshot 2024-06-07 155219](https://github.com/UMEP-dev/SUEWS/assets/1802656/bf07d701-6685-4f14-86b5-581b173f8d59)
![Screenshot 2024-06-07 155241](https://github.com/UMEP-dev/SUEWS/assets/1802656/561bb82e-a85a-46ca-b369-d147cc966d45)

**Additional context**

**Comment by sunt05** [comment]
Thanks for reporting the issue - which supy version are you using?

Or, please try the latest dev version:
```
pip install supy==2024.5.24.dev0
```

and see the issue persists?

**Comment by putupass** [comment]
Thank you for your response and solution.
Your solution works and solves the issue.
