### ISSUE TITLE
Issues installing SUEWS from different machines and branches

### ISSUE THREAD

**Issue by dayantur** [UMEP-dev/SUEWS#291]
Hi all, 
sorry for the long message, but I wanted to cover everything. @MatthewPaskin and I have been having issues installing SUEWS and have tried different strategies, but we still cannot find where the problem is.
 
On Tuesday 22 Oct (morning) I followed each step in UMEP-dev/SUEWS/tree/sunt05/issue283/README.md to install SUEWS on my Mac machine (M3), so:
 
- initialised the submodule
- created the environment with mamba
- activated
- done the make dev
 
And managed to (apparently) install everything. 
But when I tried to run supy from a python script, I got an error:
 
```
(suews-dev) silviarognone@Silvias-MacBook-Pro fortran_c_comparison % python run_supy.py
ninja: error: '/private/var/folders/wq/g91nr22952ggrpqpwsgw6h4c0000gn/T/pip-build-env-65fmpqai/overlay/bin/f90wrap', needed by 'src/supy_driver/f90wrap_suews_ctrl_type.f90', missing and no known rule to make it
Traceback (most recent call last):
  File "/opt/anaconda3/envs/suews-dev/lib/python3.12/site-packages/_supy_editable_loader.py", line 345, in _rebuild
    subprocess.run(self._build_cmd, cwd=self._build_path, env=env, stdout=subprocess.DEVNULL, check=True)
  File "/opt/anaconda3/envs/suews-dev/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/anaconda3/envs/suews-dev/bin/ninja']' returned non-zero exit status 1.
  
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/silviarognone/Documents/UrbanClimate/SUEWS-STEBBS/fortran_c_comparison/run_supy.py", line 2, in <module>
    import supy as sp
  File "/opt/anaconda3/envs/suews-dev/lib/python3.12/site-packages/_supy_editable_loader.py", line 311, in find_spec
    tree = self._rebuild()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/suews-dev/lib/python3.12/site-packages/_supy_editable_loader.py", line 347, in _rebuild
    raise ImportError(f're-building the {self._name} meson-python editable wheel package failed') from exc
ImportError: re-building the supy meson-python editable wheel package failed
```
 
I tried the same procedure from the beginning in a new environment on another Mac machine (Intel) and got the same error as well. After that, Matthew tried to do the make dev from a working environment (that was working until Friday 18 Oct), and got the same error. Matthew then tried from another (Windows) machine, creating a new env and re-do the make dev from there, but got the same error again. This morning me and Matthew tried to create a new mamba environment (one on his Windows machine, one on my Mac M3) from the master branch UMEP-dev/SUEWS/ and, again, the same error. So we have 4 machines, and different mamba envs (one of them was working until Frid) that are giving the same error from both master and sunt05/issue283 branch of SUEWS.
 
We checked the release dates of ninja, wheel, and meson-python versions used in the mamba envs and they are all before Friday. But we noticed that meson package in the mamba envs is version 1.6.0, the latest one, released on Oct 20 (Sunday). That seems suspicious, but also might be a chance. We indeed tried to downgrade one env to run with meson 1.5.1 (meson version of the working env from Matthew) but got the same error again.

**Is `supy_debug-xxxxxxxx.zip` generated?**
n.d.

**Screenshots**
n.d.

**Additional context**
n.d.

**Comment by sunt05** [comment]
Hi @dayantur, thanks for reporting this. I can reproduce the error with `meson==1.5.2`.

I suspect there's an upstream issue. 

As a workaround for now, please install to your system location from the SUEWS root directory:

```bash
python -m pip install .
```

**Comment by MatthewPaskin** [comment]
Thanks, this solution works for me within the mamba environment. This also removes the error that used to occur when importing supy that f90wrap is missing - although this error did not appear to impact the SUEWS runs.

**Comment by dayantur** [comment]
Many thanks @sunt05, no errors also from my side.
I tried both within a new conda env and system-wide, and supy is running!

**Comment by sunt05** [comment]
Hi @MatthewPaskin @dayantur 

I've just updated the makefile recipe `dev` [here](https://github.com/UMEP-dev/SUEWS/commit/199d980bc471ee9984704d1d9711149320167cfb) to enhance robustness and convenience. Local installation using `make dev` will no longer result in an `import` error. Additionally, any changes made during development (e.g., modifying the suews f95 code) will automatically trigger a rebuild when you `import supy`, thanks to Meson's file tracking capability.

I believe the issue can be closed now, but please re-open it if it persists on your end.
