### ISSUE TITLE
prototype SPARTACUS coupling

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/SUEWS#41]
Use [SPARTACUS](https://github.com/Urban-Meteorology-Reading/spartacus-surface) as the radiation module in SUEWS to account for the effects of complex urban morphology.

**Comment by rarygit** [comment]
This would be very interesting!

Maybe keep the name as "spartacus-surface"?  So that it is not confused with "spartacus" on GitHub. https://github.com/SAP/spartacus

**Comment by sunt05** [comment]
thanks @rarygit for the attention! please stay tuned and more surprises (in a beneficial sense) will come in 😉

**Comment by sunt05** [comment]
as the prototype is now done; move onto more specific issues/task.
