### ISSUE TITLE
Problem with T2 values caused by `ldown_option`

### ISSUE THREAD

**Issue by Empanag** [UMEP-dev/SUEWS#47]
**Describe the bug**
hi, i'm using SUEWS for a grid in city of Heraklion at Crete. The model produce some values from the T 2m that are very low, reaching -40 C that is for sure unreal.

**Desktop (please complete the following information):**
 - OS: windows 10
 - SuPy Version 2021.2.3 (I m using python compiler not QGIS)

**Screenshots**
![image](https://user-images.githubusercontent.com/61833032/112841250-f092f380-90a8-11eb-8b2f-f7a7cc967fc0.png)

**Data**
[suews.zip](https://github.com/UMEP-dev/UMEP/files/6221853/suews.zip)

**Comment by sunt05** [comment]
Observed Ld values are not properly picked by calculation kernel.

**Comment by Empanag** [comment]
So what could i do to run correctly the model? Is this a problem that will be fixed by update of supy?

**Comment by sunt05** [comment]
Please update your supy to the latest release `2021.3.30`, in which this issue should be fixed.
If so, please consider closing this issue; otherwise, feel free to let me know and report the numbers of problematic grids.

**Comment by Empanag** [comment]
okey i 'm running now the model using supy 2021.3.30 and i 'll let you know.

**Comment by sunt05** [comment]
great! if this issue is resolved, please close it; we can open new ones if any appears.
