### ISSUE TITLE
documentation for SS

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/SUEWS#60]
- [x] brief intro to scientific background of SU (can ref to proper papers)
- [x] #76
- [x] SS input
   - [x] description for SS specific input: move to input section 
   - [x] SU related options in RunControl.nml: move to input section
- [x] #77

all these are written down in [a separate document](https://livereadingac-my.sharepoint.com/:p:/r/personal/wa916280_reading_ac_uk/_layouts/15/Doc.aspx?sourcedoc=%7B930B7B73-0842-4839-B107-59237DC145A7%7D&file=SUEWS-SS.pptx&action=edit&mobileredirect=true) by @LewisB7 but need to be transferred to the online RTD site.

**Comment by sunt05** [comment]
1. description for SU specific input files
2. description for SU specific output files
3. SU related options in RunControl.nml
4. brief intro to scientific background of SU (can ref to proper papers)

**Comment by sunt05** [comment]
a preliminary version based on @LewisB7 's slides is up and running; more cleaning and re-organisation is yet needed.

https://suews.readthedocs.io/en/spartacus_clean_up/parameterisations-and-sub-models.html#spartacus-surface-ss

**Comment by LewisB7** [comment]
I have left comments in the SUEWS-SS documentation at https://suews.readthedocs.io/en/spartacus_clean_up/parameterisations-and-sub-models.html#id22
