### ISSUE TITLE
SS specific output files: move to output section

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/SUEWS#77]
- [ ] output table in csv: an example: [display form](https://suews.readthedocs.io/en/latest/output_files/output_files.html#ssss-yyyy-rsl-tt-txt) and [csv](https://github.com/UMEP-dev/SUEWS/blob/master/docs/source/output_files/SSss_YYYY_RSL_TT.csv)

**Comment by LewisB7** [comment]
Hi Ting,
I have made the output file csv. Let me know if it is not what you expected.
Cheers,
Lewis

[output_table_documentation.csv](https://github.com/UMEP-dev/SUEWS/files/7875000/output_table_documentation.csv)
