### ISSUE TITLE
How to use supy-driver version 2021a2 when building SUEWS 2021a

### ISSUE THREAD

**Issue by rarygit** [UMEP-dev/SUEWS#81]
OS: Ubuntu 20.04

Previously I had installed supy and supy-driver in a conda environment (Python v3.9).
The version installed by pip3 was v2021a2.
As described here: https://github.com/UMEP-dev/SuPy/issues/42

Afterwards I then built SUEWS 2021a, including spartacus.
git clone https://github.com/UMEP-dev/SUEWS.git

(inside .../SUEWS-SourceCode/):  
git submodule init 
git submodule update

submodule update needed SSH permissions, so I used HTTPS instead, as below

(inside .../SUEWS-SourceCode/ext_lib)  
git clone https://github.com/Urban-Meteorology-Reading/spartacus-surface.git

(inside .../SUEWS-SourceCode/):  
make

The Linux binary was built in the Release folder: SUEWS_2021a
However supy-driver was not built (error), as this was v2021a3 and v2021a2 was already installed previously, as above.

As a work-around, I replaced the SUEWS 2021a supy-driver 2021a3 folder with supy-driver v2021a2.

Reran make (without clean) and there seemed to be no errors with supy-driver v2021a2

I then ran the tests

(inside .../SUEWS-SourceCode/): 
make test 

I have attached the log file (terminal output)
For ease of reading, I have divided the output from "make" and from "make test" at line 4684

Looking at the attached log file: 
what are the errors between lines 4653 to 4690 ?
why does "make test" hang at line 7576:  STOP finished, and not return the command prompt?
I manually closed it with ctrl+c

Thanks for any suggestions.
  
[LOG_make & make tests_SUEWS 2021a.zip](https://github.com/UMEP-dev/SUEWS/files/8001923/LOG_make.make.tests_SUEWS.2021a.zip)

**Comment by sunt05** [comment]
Hi @rarygit, thanks for "tasting" the building process, which is not meant to ordinary users but I'm glad you have interests.
I'll use your case and expand the development section in the manual, which may hopefully address this issue.
I'll keep you updated.

**Comment by rarygit** [comment]
Aha, now I understand.
OK, I will leave this as answered.
Thanks for keeping me updated!
