### ISSUE TITLE
Negative zd_RSL due to small FAI and large Lc

### ISSUE THREAD

**Issue by XiaoxiongXie** [UMEP-dev/SUEWS#88]
https://github.com/UMEP-dev/SUEWS/blob/538bda2640f95a68c10a577defda39d1290309f2/SUEWS-SourceCode/src/suews_phys_rslprof.f95#L868

If `FAI` is small, `Lc` can become too large and then gives negative `zd_RSL`.

**Comment by sunt05** [comment]
https://github.com/UMEP-dev/SUEWS/blob/538bda2640f95a68c10a577defda39d1290309f2/SUEWS-SourceCode/src/suews_phys_rslprof.f95#L742-L755

**Comment by sunt05** [comment]
combine both above we can infer the condition for positive `zd`:
```
FAI > beta^2 (1 - sfrBldg)
```
where sfrBldg is the land cover fraction of buildings.
