### ISSUE TITLE
Additional outputs from SUEWS-SPARTACUS: diffuse radiation at ground level

### ISSUE THREAD

**Issue by megstretton** [UMEP-dev/SUEWS#98]
One output of SPARTACUS-Surface is the diffuse shortwave radiation at ground level into a vertical surface. This is not a current output of SUEWS-SPARTACUS but would be useful for the prediction of mean radiant temperature.

**Comment by sunt05** [comment]
> One output of SPARTACUS-Surface is the diffuse shortwave radiation at ground level into a vertical surface. 

@megstretton are you referring to the diffuse shortwave radiation flux at a **single** ground level: 

https://github.com/Urban-Meteorology-Reading/spartacus-surface/blob/master/radsurf/radsurf_canopy_flux.F90#L33

or **multiple** vertical levels:

https://github.com/Urban-Meteorology-Reading/spartacus-surface/blob/master/radsurf/radsurf_canopy_flux.F90#L58-L63
?

**Comment by megstretton** [comment]
@sunt05 I'm referring to the diffuse flux into a **vertical surface** at ground level - which is used for mean radiant temperature calculations. At this line:

https://github.com/Urban-Meteorology-Reading/spartacus-surface/blob/5c3a997b7abc8840434a709216409c91498125a1/radsurf/radsurf_canopy_flux.F90#L48

**Comment by sunt05** [comment]
@megstretton this—also those requested in #97—should be in now: please check out the latest master and give it try.

One thing I'm not quite certain is the quantity—based on the code and related comments, there seems to have some rescaling/normalisation involved.

Please open a new issue if it is the case.

Also show some testing results that can help us more rapidly identify the issue. Thanks!
