### ISSUE TITLE
Issues with longwave fluxes in SUEWS-SPARTACUS

### ISSUE THREAD

**Issue by megstretton** [UMEP-dev/SUEWS#99]
Longwave fluxes in SUEWS when using the SPARTACUS treatment of radiation seem incorrect. The net Longwave radiation on a test case is positive, leading to a positive Q* overnight.

I have examined the output files to check for possible confusion of longwave flux variables, however these all appear to be correct.

**Comment by sunt05** [comment]
the issue is in the way how ground temperature is weighted averaged by area: now fixed by correcting the surface cover fractions used in the averaging.
